#
# Forge modules
#
forge 'http://forge.puppetlabs.com'

mod 'choria/choria', '0.31.0'
mod 'choria/mcollective', '0.14.6'
mod 'choria/mcollective_agent_filemgr', '2.1.0'
mod 'choria/mcollective_agent_package', '5.5.1'
mod 'choria/mcollective_agent_puppet', '2.5.0'
mod 'choria/mcollective_agent_service', '4.1.0'
mod 'choria/mcollective_agent_shell', '1.1.0'
mod 'choria/mcollective_choria', '0.22.2'
mod 'choria/mcollective_util_actionpolicy', '3.3.0'
mod 'puppet/chrony', '5.0.0'
mod 'puppet/extlib', '7.5.1'
mod 'puppet/python', '8.0.0'
mod 'puppet/r10k', '15.1.0'
mod 'puppet/systemd', '9.4.0'
mod 'puppet/yum', '7.3.0'
mod 'puppetlabs/apache', '13.1.0'
mod 'puppetlabs/augeas_core', '2.0.1'
mod 'puppetlabs/concat', '9.1.0'
mod 'puppetlabs/cron_core', '2.0.2'
mod 'puppetlabs/inifile', '6.3.1'
mod 'puppetlabs/java', '11.2.0'
mod 'puppetlabs/postgresql', '10.6.1'
mod 'puppetlabs/puppetdb', '8.1.0'
mod 'puppetlabs/selinux_core', '2.0.1'
mod 'puppetlabs/stdlib', '9.7.0'
mod 'puppetlabs/yumrepo_core', '3.0.1'
mod 'theforeman/puppet', '22.1.0'
mod 'vchepkov/puppetboard', '5.1.1'
